/** Modules generated by scripts/build.mjs at bundle time (not resolvable by tsc / vitest). */
declare module 'figmadeck:compress-worker' {
  /** Bundled source of src/ui/compress.worker.ts (an IIFE script), started from a blob: / data: URL. */
  const code: string;
  export default code;
}
